version: '3.8'

services:
  json-server:
    image: docker.io/backplane/json-server:latest
    command: ["--watch", "db.json"]
    ports:
      - "4000:3000"
    volumes:
      - ./json-server:/work
  rdf4j:
    image: docker.io/eclipse/rdf4j-workbench:latest
    environment:
      JAVA_OPTS: "-Xms1g -Xmx4g"
    ports:
      - "8080:8080"
